# Generated by Django 4.2.7 on 2024-11-23 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
    ]

    operations = [
    ]
